#!/usr/bin/perl

use strict ;
use warnings ;
use Carp 'croak', 'carp'; 

use File::Basename;
use IPC::System::Simple qw(systemx runx capturex $EXITVAL);
use String::ShellQuote ;

our $verbose ;
our $noexecute ;
our $lexeronly ;
our $namedtypes ;
our $ocaml ;
our $subcommand ;
our $testcase ;
our $showdfa ;
our $eeargs ; 

unless (defined $ENV{TOP}) {
  my $p = $0 ;
  $p =~ s,/tests/tools/dtest-runner,,;
  $ENV{TOP} = $p ;
}

{
  while (@ARGV) {
    if ($ARGV[0] eq '-v') {
      shift @ARGV ;
      $verbose = 1;
    }
    elsif ($ARGV[0] eq '-n') {
      shift @ARGV ;
      $noexecute = 1;
    }
    elsif ($ARGV[0] eq '--lexer-only') {
      shift @ARGV ; 
      $lexeronly = 1 ;
    }
    elsif ($ARGV[0] eq '--ocaml') {
      shift @ARGV ; 
      $ocaml = 1 ;
    }
    elsif ($ARGV[0] eq '--named-types') {
      shift @ARGV ; 
      $namedtypes = 1 ;
    }
    elsif ($ARGV[0] eq '--show-dfa') {
      shift @ARGV ; 
      $showdfa = 1 ;
    }
    elsif ($ARGV[0] eq '--ee-args') {
      shift @ARGV ; 
      $eeargs = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'run') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'compare') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'json-entry-exit') {
      $subcommand = shift @ARGV ;
    }
    else { last ; }
  }

  die "no subcomamnd specified" unless defined $subcommand ;

  die "subcommand must be either {run,compare,json-entry-exit}"
      unless ($subcommand eq 'run' || $subcommand eq 'compare' || $subcommand eq 'json-entry-exit') ;

  if ($subcommand eq 'compare') {
    compare() ;
    exit ;
  }

  my $args = {} ;
  if (@ARGV) {
    $testcase = shift @ARGV ;
    $args->{'inputfile'} = "expected/input.$testcase" ;
  }
  else {
    $testcase = 'DEFAULT' ;
    $args->{'inputfile'} = "expected/input" ;
  }

  print STDERR "testcase is $testcase\n" if ($verbose) ;

  my $testsuff = "" ;
  if ($ocaml) {
    $testsuff .= "-ocaml" ;
  }
  else {
    $testsuff .= "-python" ;
  }
  $testsuff .= "-lexer-only" if ($lexeronly) ;
  $testsuff .= "-named-types" if ($namedtypes) ;

  my $testdir = "_build/${testcase}${testsuff}" ;
  $args->{testdir} = $testdir ;

  v_system("mkdir -p $testdir") unless -d $testdir ;
  if ($subcommand eq 'run') {
    runtest($args) ;
  }
  elsif ($subcommand eq 'json-entry-exit') {
    entry_exit($args) ;
  }
}

sub runtest {
  my $h = shift ;
  my $testdir = $h->{testdir} ;
  my $inputfile = $h->{inputfile};
  my $cmd = "" ;
  if ($main::ocaml) {
    $cmd .= "../../test.opt test --json-log-file=json.log.RAW " ;
#    $cmd .= "--lexer-only " if ($main::lexeronly) ;

  }
  elsif ($main::lexeronly) {
    $cmd .= "python3 ../../TestLexer.py " ;
  }
  else {
    $cmd .= "python3 ../../Test.py " ;
  }

  $cmd .= "--show-dfa " if ($main::showdfa) ;
  $cmd .= "--named-types " if ($main::namedtypes) ;
  
  $cmd .= " ../../$inputfile" ;
  $cmd = "(cd $testdir && $cmd > output 2> errors)" ;
  v_system($cmd) ;
  v_system("(cd $testdir && jq -S . json.log.RAW > json.log.NEW && mv json.log.NEW json.log)") ;
}

sub entry_exit {
  my $h = shift ;
  my $testdir = $h->{testdir} ;

  my $cmd = "$ENV{TOP}/tests/replay_util.opt entry-exit-depth $eeargs json.log > json.ee.log" ;
  $cmd = "(cd $testdir && $cmd)" ;
  v_system($cmd) ;
}

sub compare {
  my @l = glob("_build/*") ;
  foreach my $testdir (@l) {
    my $expectedoutput ;
    my $expectederrors ;
    # compare -ocaml to -python
    if ($testdir =~ /ocaml/) {
      my $comparedir = $testdir ;
      $comparedir =~ s,ocaml,python, ;
      $expectedoutput = "$comparedir/output" ;
      $expectederrors = "$comparedir/errors" ;

      unless (-f $expectedoutput && -f $expectederrors) {
	carp "compare: testdir $testdir couldn't be diffed b/c comparedir $comparedir didn't have both {output,errors}" ;
	next ;
      }
    }
    # DEFAULT-python has expected-files
    elsif ($testdir =~ m,^_build/DEFAULT-python$,) {
      $expectedoutput = "expected/output" ;
      $expectederrors = "expected/errors" ;
    }
    # {NAME}-python has expected-files
    elsif ($testdir =~ m,^_build/([^-]+)-python$,) {
      $expectedoutput = "expected/output.$1" ;
      $expectederrors = "expected/errors.$1" ;
    }
    # any other python -might- have expected-files
    # if it doesn't, then skip
    elsif ($testdir =~ m,^_build/([^-]+)-python(.*)$,) {
      my $name = $1 ;
      my $type = $2 ;
      $name = "" if $name eq 'DEFAULT' ;
      my $namesuff = "" ;
      $namesuff = ".$name" if $name ne "" ;
      $expectedoutput = "expected/output${type}${namesuff}"
	  if (-f "expected/output${type}${namesuff}") ;
      $expectederrors = "expected/errors${type}${namesuff}"
	  if (-f "expected/errors${type}${namesuff}") ;

      unless (defined $expectedoutput || defined $expectederrors) {
	print STDERR "SKIP $testdir (neither expected-{output,errors} specified)!\n" ;
	next ;
      }
      $expectedoutput = "" unless (defined $expectedoutput) ;
      $expectederrors = "" unless (defined $expectederrors) ;
    }

    unless (-f $expectedoutput) {
      carp "compare: testdir $testdir: expected-output <<$expectedoutput>> non-existent (assuming /dev/null suffices)" if ($main::verbose) ;
      $expectedoutput = "/dev/null" ;
    }
    unless (-f $expectederrors) {
      carp "compare: testdir $testdir: expected-errors <<$expectederrors>> non-existent (assuming /dev/null suffices)" if ($main::verbose)  ;
      $expectederrors = "/dev/null" ;
    }

    print STDERR "DIFF $testdir\n" ;
    v_system("diff -Bwiu $expectedoutput ${testdir}/output") ;
    v_system("diff -Bwiu $expectederrors ${testdir}/errors") ;
  }
}

sub v_systemx {
  croak( "v_systemx: must specify exit codes") unless (ref($_[0]) eq 'ARRAY') ;
  my $codes = shift ;
  my @cmd = @{ shift @_ } ;
  my %args = @_ ;


  print STDERR join(' ', "$0:", map { shell_quote($_) } @cmd)."\n" if $main::verbose > 0;

  return runx($codes, @cmd) unless $noexecute ;
}

sub f_read {
  my $f = shift;
  open(F,"<$f") || die "cannot open $f for reading";
  my @l = <F>;
  close(F);
  return (wantarray ? @l : join('', @l)) ;
}

sub v_system {
  my $cmd = shift;
  print STDERR "<<$cmd>>\n" if ($main::verbose);
  system $cmd unless ($main::noexecute) ;
}
