#!/usr/bin/perl

use strict ;
use IPC::System::Simple qw(systemx runx capturex $EXITVAL);
use String::ShellQuote ;
use File::Basename;

our $verbose ;
our $noexecute ;
our @genargs = ("--template-dir=fixtures/antlrtest.7") ;

$ENV{'TOP'} = ".." ;

{
  my @patterns ;
  my @exclude ;
  my $subcommand ;
  while (@ARGV) {
    if ($ARGV[0] eq '-v') {
      shift @ARGV ;
      $verbose = 1;
    }
    elsif ($ARGV[0] eq '-n') {
      shift @ARGV ;
      $noexecute = 1;
    }
    elsif ($ARGV[0] eq '--descriptor-pattern') {
      shift @ARGV ; 
      push(@patterns, shift @ARGV) ;
    }
    elsif ($ARGV[0] eq '--exclude') {
      shift @ARGV ; 
      push(@exclude, shift @ARGV) ;
    }
    elsif ($ARGV[0] eq 'realclean') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'generate') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'python-prepare') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'depend') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'compile') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'python-test') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'clean') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'compare-atns') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'save-json-log') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'compare-json-log') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'update-pertest') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'ocaml-compile') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'ocaml-test') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'ocaml-compare') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'full') {
      $subcommand = shift @ARGV ;
    }
    else { last ; }
  }

  die "no subcomamnd specified" unless defined $subcommand ;

  my @full1 = qw(python-prepare python-test compare-atns update-pertest) ;
  my @full2 = qw(ocaml-compile ocaml-test ocaml-compare) ;

  my @testfiles = @ARGV ;

  unless (int(@testfiles) || int(@patterns)) {
    @patterns = (
      "$ENV{'TOP'}/tests/fixtures/descriptors/*/*.txt",
      "$ENV{'TOP'}/tests/fixtures/custom-descriptors/*/*.txt",
	) ;
    @exclude = ("Performance") unless (int(@exclude)) ;
  }
  if (int(@patterns)) {
    push(@testfiles, glob_tests(@patterns)) ;
  }
  foreach my $pat (@exclude) {
    @testfiles = exclude_tests($pat, @testfiles) ;
  }

  if ($subcommand eq 'realclean') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["rm", "-rf", $dir]) ;
      my $dirdir = dirname($dir) ;
      my @cl = glob("$dirdir/*") ;
      if (! int(@cl)) {
	v_systemx([0], ["rm", "-rf", $dirdir]) ;
      }
    }
  }
  elsif ($subcommand eq 'generate') {
    foreach my $tf (@testfiles) {
      generate($tf) ;
    }
  }
  elsif ($subcommand eq 'clean') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "clean"]) ;
    }
  }
  elsif ($subcommand eq 'python-prepare') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "python-prepare"]) ;
    }
  }
  elsif ($subcommand eq 'depend') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "depend"]) ;
    }
  }
  elsif ($subcommand eq 'compile') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "compile"]) ;
    }
  }
  elsif ($subcommand eq 'python-test') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "python-test"]) ;
    }
  }
  elsif ($subcommand eq 'compare-atns') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "compare-atns"]) ;
    }
  }

  elsif ($subcommand eq 'save-json-log') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "save-json-log"]) ;
    }
  }

  elsif ($subcommand eq 'compare-json-log') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "compare-json-log"]) ;
    }
  }
  elsif ($subcommand eq 'update-pertest') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "update-pertest"]) ;
    }
  }
  elsif ($subcommand eq 'ocaml-compile') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "ocaml-compile"]) ;
    }
  }
  elsif ($subcommand eq 'ocaml-test') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "ocaml-test"]) ;
    }
  }
  elsif ($subcommand eq 'ocaml-compare') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "ocaml-compare"]) ;
    }
  }
  elsif ($subcommand eq 'full') {
    foreach my $tf (@testfiles) {
      my $txt = f_read($tf) ;
      if ($txt =~ m,\[skip\].*Python3,s) {
	print STDERR "SKIP $tf\n";
	next ;
      }
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      v_systemx([0], ["rm", "-rf", $dir]) ;
      generate($tf) ;
      v_systemx([0], ["make", "-C", $dir, @full1]) ;
      v_systemx([0], ["make", "-C", $dir, @full2]) ;
    }
  }

  else { die "unrecognized subcommand <<$subcommand>>" ; }

}

sub generate {
  my $tf = shift ;
  my $p = test_name($tf) ;

  v_systemx([0], ["$ENV{'TOP'}/tests/antlrtest_util.opt", "generate", @genargs,
		  "-d", "_generated", "-n", $p,
		  $tf]) ;
}

# "$ENV{'TOP'}/tests/fixtures/descriptors/*/*.txt"
sub  glob_tests {
  my  @l ;
  foreach my $pat (@_) {
    my @globbed = glob($pat) ;
    push (@l, @globbed) ;
  }
  return @l ;
}  

sub test_name {
  my $p = shift ;
  $p =~ s,^.*/([^/]+/[^/]+.txt)$,$1,;
  $p =~ s,\.txt$,, ;
  return $p ;
}

sub exclude_tests {
  my $pat = shift;
  my @l ;
  foreach my $p (@_) {
    push (@l, $p) unless ($p =~ m,$pat,) ;
  }
  return @l ;
}

sub v_systemx {
  croak( "v_systemx: must specify exit codes") unless (ref($_[0]) eq 'ARRAY') ;
  my $codes = shift ;
  my @cmd = @{ shift @_ } ;
  my %args = @_ ;


  print STDERR join(' ', "$0:", map { shell_quote($_) } @cmd)."\n" if $main::verbose > 0;

  return runx($codes, @cmd) unless $noexecute ;
}

sub f_read {
  my $f = shift;
  open(F,"<$f") || die "cannot open $f for reading";
  my @l = <F>;
  close(F);
  return (wantarray ? @l : join('', @l)) ;
}
