#!/usr/bin/perl

use strict ;

{
  my @l = () ;
  foreach my $f (@ARGV) {
    my $txt = f_read($f) ;
    my $tag = $f ;
    unless ($tag =~ m,.*/([^/]+)\.sexp$,) {
      die "malformatted file $f" ;
    }
    push(@l, [$1, $txt]) ;
  }

  print "(\n";
  foreach my $p (@l) {
    my ($tag, $txt) = @{$p} ;
    print <<"EOF"
("$tag"
$txt)
EOF
  }
  print ")\n";

}

sub f_read {
  my $f = shift;
  open(F,"<$f") || die "cannot open $f for reading";
  my @l = <F>;
  close(F);
  return (wantarray ? @l : join('', @l)) ;
}
