include $(TOP)/config/Makefile.config
include $(TOP)/config/Makefile.shared
include $(TOP)/config/Makefile.tools

META_PACKAGES=fmt,re

META: mk_meta.ML
	$(NOVERBOSE) cppo -I $(TOP) mk_meta.ML > mk_meta.ml
	$(LAUNCH) $(OCAMLFIND) ocamlc -linkpkg -linkall -package $(META_PACKAGES) mk_meta.ml -o mk_meta
	$(NOVERBOSE) ./mk_meta > META

EXTERNAL=$(shell $(LAUNCH) $(OCAMLFIND) query -predicates byte -format '%m' $(ALLPACKAGES) | grep local-install)

depend::
	$(NOVERBOSE) echo "$(CMO) $(CMI) $(CMX): $(EXTERNAL)" > .depend.NEW
	$(LAUNCH) $(YAWRAP) $(OCAMLFIND) ocamldep -package $(PACKAGES) -- $(ALLSRC) >> .depend.NEW
	$(NOVERBOSE) mv .depend.NEW .depend

-include .depend
