ARGS+=" -e DFA.__init__"
ARGS+=" -e DFA.setPrecedenceStartState"
ARGS+=" -e DFA.set_s0"
ARGS+=" -e DFA.states_add"
ARGS+=" -e DFA.states_get"
ARGS+=" -e DFA.states_len"

ARGS+=" -e DFAState.__init__"
ARGS+=" -e DFAState.makeEdges"
ARGS+=" -e DFAState.set_configs"
ARGS+=" -e DFAState.setEdge"
ARGS+=" -e DFAState.set_isAcceptState"
ARGS+=" -e DFAState.set_lexerActionExecutor"
ARGS+=" -e DFAState.set_predicates"
ARGS+=" -e DFAState.set_prediction"
ARGS+=" -e DFAState.set_requiresFullContext"
ARGS+=" -e DFAState.set_stateNumber"
