#!/usr/bin/perl

use strict ;
use IPC::System::Simple qw(systemx runx capturex $EXITVAL);
use String::ShellQuote ;
use File::Basename;

our $verbose ;
our $noexecute ;
our @genargs = ("--template-dir=fixtures/antlrtest.3") ;

$ENV{'TOP'} = ".." ;

{
  my @patterns ;
  my @exclude ;
  my $subcommand ;
  while (@ARGV) {
    if ($ARGV[0] eq '-v') {
      shift @ARGV ;
      $verbose = 1;
    }
    elsif ($ARGV[0] eq '-n') {
      shift @ARGV ;
      $noexecute = 1;
    }
    elsif ($ARGV[0] eq '--descriptor-pattern') {
      shift @ARGV ; 
      push(@patterns, shift @ARGV) ;
    }
    elsif ($ARGV[0] eq '--exclude') {
      shift @ARGV ; 
      push(@exclude, shift @ARGV) ;
    }
    elsif ($ARGV[0] eq 'realclean') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'generate') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'prepare') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'test') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'clean') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'compare-atns') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'save-json-log') {
      $subcommand = shift @ARGV ;
    }
    elsif ($ARGV[0] eq 'compare-json-log') {
      $subcommand = shift @ARGV ;
    }
    else { last ; }
  }

  my @testfiles = @ARGV ;

  unless (int(@testfiles) || int(@patterns)) {
    @patterns = ("$ENV{'TOP'}/tests/fixtures/descriptors/*/*.txt") ;
    @exclude = ("Performance") unless (int(@exclude)) ;
  }
  if (int(@patterns)) {
    push(@testfiles, glob_tests(@patterns)) ;
  }
  foreach my $pat (@exclude) {
    @testfiles = exclude_tests($pat, @testfiles) ;
  }

  if ($subcommand eq 'realclean') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["rm", "-rf", $dir]) ;
      my $dirdir = dirname($dir) ;
      my @cl = glob("$dirdir/*") ;
      if (! int(@cl)) {
	v_systemx([0], ["rm", "-rf", $dirdir]) ;
      }
    }
  }
  elsif ($subcommand eq 'generate') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      v_systemx([0], ["$ENV{'TOP'}/tests/antlrtest_util.opt", "generate", @genargs,
		      "-d", "_generated/$p",
		      $tf]) ;
    }
  }
  elsif ($subcommand eq 'clean') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "clean"]) ;
    }
  }
  elsif ($subcommand eq 'prepare') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "prepare"]) ;
    }
  }
  elsif ($subcommand eq 'test') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "all"]) ;
    }
  }
  elsif ($subcommand eq 'compare-atns') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "compare-atns"]) ;
    }
  }

  elsif ($subcommand eq 'save-json-log') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "save-json-log"]) ;
    }
  }

  elsif ($subcommand eq 'compare-json-log') {
    foreach my $tf (@testfiles) {
      my $p = test_name($tf) ;
      my $dir = "_generated/$p" ;
      next unless (-d $dir) ;
      v_systemx([0], ["make", "-C", $dir, "compare-json-log"]) ;
    }
  }

  else { die "unrecognized subcommand <<$subcommand>>" ; }

}

# "$ENV{'TOP'}/tests/fixtures/descriptors/*/*.txt"
sub  glob_tests {
  my  @l ;
  foreach my $pat (@_) {
    my @globbed = glob($pat) ;
    push (@l, @globbed) ;
  }
  return @l ;
}  

sub test_name {
  my $p = shift ;
  $p =~ s,^.*/([^/]+/[^/]+.txt)$,$1,;
  $p =~ s,\.txt$,, ;
  return $p ;
}

sub exclude_tests {
  my $pat = shift;
  my @l ;
  foreach my $p (@_) {
    push (@l, $p) unless ($p =~ m,$pat,) ;
  }
  return @l ;
}

sub v_systemx {
  croak( "v_systemx: must specify exit codes") unless (ref($_[0]) eq 'ARRAY') ;
  my $codes = shift ;
  my @cmd = @{ shift @_ } ;
  my %args = @_ ;


  print STDERR join(' ', "$0:", map { shell_quote($_) } @cmd)."\n" if $main::verbose > 0;

  return runx($codes, @cmd) unless $noexecute ;
}

