#!/bin/bash -x

echo "TOP: " ${TOP}

cp ${TOP}/tests/fixtures/grammar-lib/Lex* grammars/
cp ${TOP}/tests/fixtures/grammar-lib/STG2Lexer.g4 grammars/

echo "module L_constants = STG2Lexer_constants" > ActionFuns_STG2.ml 
cat ${TOP}/tests/fixtures/pertest-files/antlr4/STG2/ActionFuns_STG2.ml >> ActionFuns_STG2.ml 
cp ${TOP}/tests/fixtures/pertest-files/antlr4/STG2/translation.json grammars/STG2Lexer-translation.json
