#!/bin/bash -x

echo "TOP: " ${TOP}

cp ${TOP}/tests/fixtures/grammar-lib/Lex* grammars/
cp ${TOP}/tests/fixtures/grammar-lib/ST[012]Lexer.g4 grammars/
cp ${TOP}/tests/fixtures/grammar-lib/STG[02]Lexer.g4 grammars/

cp ${TOP}/tests/fixtures/pertest-files/antlr4/ST0/translation.json grammars/ST0Lexer-translation.json
echo "module L_constants = ST0Lexer_constants" > ActionFuns_ST0.ml 
cat ${TOP}/tests/fixtures/pertest-files/antlr4/ST0/ActionFuns_ST0.ml >> ActionFuns_ST0.ml 

cp ${TOP}/tests/fixtures/pertest-files/antlr4/ST1/translation.json grammars/ST1Lexer-translation.json
echo "module L_constants = ST1Lexer_constants" > ActionFuns_ST1.ml 
cat ${TOP}/tests/fixtures/pertest-files/antlr4/ST1/ActionFuns_ST1.ml >> ActionFuns_ST1.ml 

cp ${TOP}/tests/fixtures/pertest-files/antlr4/ST2/translation.json grammars/ST2Lexer-translation.json
echo "module L_constants = ST2Lexer_constants" > ActionFuns_ST2.ml 
cat ${TOP}/tests/fixtures/pertest-files/antlr4/ST2/ActionFuns_ST2.ml >> ActionFuns_ST2.ml 

cp ${TOP}/tests/fixtures/pertest-files/antlr4/STG0/translation.json grammars/STG0Lexer-translation.json

echo "module L_constants = STG2Lexer_constants" > ActionFuns_STG2.ml 
cat ${TOP}/tests/fixtures/pertest-files/antlr4/STG2/ActionFuns_STG2.ml >> ActionFuns_STG2.ml 
cp ${TOP}/tests/fixtures/pertest-files/antlr4/STG2/translation.json grammars/STG2Lexer-translation.json
